modLoader = "javafml"
loaderVersion = "[47,)"
license = "MIT"
issueTrackerURL="https://github.com/JamCoreModding/shut-up-gl-error/issues"

[[mods]]
modId = "shut_up_gl_error"
version = "${file.jarVersion}"
displayName = "Shut Up GL Error"
displayURL="https://github.com/JamCoreModding/shut-up-gl-error"
logoFile = "icon.png"
authors = "Jamalam"
description = '''
Fixes invalid keycodes logging obnoxious and constant messages
'''

[[dependencies.shut_up_gl_error]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.shut_up_gl_error]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20,1.21)"
ordering = "NONE"
side = "BOTH"
