modLoader = "javafml"
loaderVersion = "[47,)"
license = "MIT"
issueTrackerURL="https://github.com/{{github_owner}}/{{github_repo}}/issues"

[[mods]]
modId = "{{mod_id}}"
version = "${file.jarVersion}"
displayName = "{{name}}"
displayURL="https://github.com/{{github_owner}}/{{github_repo}}"
logoFile = "icon.png"
authors = "{{author}}"
description = '''
{{description}}
'''

[[dependencies.{{mod_id}}]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.{{mod_id}}]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20,1.21)"
ordering = "NONE"
side = "BOTH"
