modLoader = "javafml"
loaderVersion = "[1,)"
license = "MIT"
issueTrackerURL="https://github.com/JamCoreModding/shut-up-gl-error/issues"

[[mods]]
modId = "shut_up_gl_error"
version = "${version}"
displayName = "Shut Up GL Error"
displayURL="https://github.com/JamCoreModding/shut-up-gl-error"
logoFile = "icon.png"
authors = "Jamalam"
description = '''
Fixes invalid keycodes logging obnoxious and constant messages
'''

[[dependencies.shut_up_gl_error]]
modId = "neoforge"
type = "required"
versionRange = "[${neoforge_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.shut_up_gl_error]]
modId = "minecraft"
type = "required"
versionRange = "[${minecraft_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.shut_up_gl_error]]
modId = "architectury"
type = "required"
versionRange = "[${architectury_version},)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.shut_up_gl_error]]
modId = "jamlib"
type = "required"
versionRange = "[${jamlib_version},)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "shut_up_gl_error.mixins.json"
